permalink: none
base_dir: /
title_prefix: Alois Cochard
ga_id: UA-348171-13

title: Alois Cochard
description: Passionate Hacker
google_analytics: UA-348171-13
show_downloads: true
theme: jekyll-theme-dinky